name: tests

on:
  workflow_run:
    workflows: [ "docker-build" ]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.actor }}/hybridleads:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up building directory
        run: |
          echo "build_dir=tests/build" >> $GITHUB_ENV

      - name: Build
        run: |
          cmake -S tests -B ${{ env.build_dir }}
          make -C ${{ env.build_dir }}

      - name: Unit Test
        run: |
          for filename in ${{ env.build_dir }}/test_*.exe; do
            ./"$filename" || continue
          done

      - name: Generate coverage reports
        run: |
          apt update && \
          apt-get install -y --no-install-recommends python3-pip && \
          pip install gcovr && \
          gcovr --xml coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
